update : workflow add then fails [2]

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -6,7 +6,6 @@ on:
   pull_request:
     branches:
       - main
-
 jobs:
   build:
     name: Test
@@ -19,11 +18,14 @@ jobs:
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
-          go-version: "1.21.6" # You can specify any Go version you need
+          go-version: "1.21.6"
 
       - name: Run tests
         run: go test -v ./...
 
-      - name: Notify on failure
-        if: failure()
-        run: echo "Test failed. Please check your code."
+      - name: Check test status
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "::error::Tests failed. Cancelling workflow."
+            exit 1
+          fi
